apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-students-test
  labels:
    app: courses-students-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-students-test
  template:
    metadata:
      labels:
        app: courses-students-test
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port=8081",
            "--backend=127.0.0.1:8080",
            "--service=courses-students-test.endpoints.courses-students-test.cloud.goog",
            "--rollout_strategy=managed",
          ]
          ports:
            - containerPort: 8081
        - name: courses-students-test
          image: gcr.io/google_cloud_project/courses-students-test:commit_sha
          envFrom:
            - secretRef:
                name: db-conn-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: courses-students-test-svc
spec:
  selector:
    app: courses-students-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
